compile:
	javac -cp .:../lib/jinterface-1.6.1.jar main/*.java

counter:
	java -cp .:../lib/jinterface-1.6.1.jar main.Counter

function:
	java -cp .:../lib/jinterface-1.6.1.jar main.GenericFunction

backend:
	java -cp .:../lib/jinterface-1.6.1.jar main.Backend

frontend:
	java -cp .:../lib/jinterface-1.6.1.jar main.Frontend

clean:
	rm main/*.class
