compile:
	javac -cp .:/usr/lib/erlang/lib/jinterface-1.9.1/priv/OtpErlang.jar main/*.java

run:
	java -cp .:/usr/lib/erlang/lib/jinterface-1.9.1/priv/OtpErlang.jar main.Backend

clean:
	rm main/*.class
